### ISSUE TITLE
Unable to build Koreader submodule

### ISSUE THREAD

**Issue by AluminumTank** [lgeek/okreader#19]
Not sure if I should put this here, but it appears that one of Koreader's dependencies has moved (https://github.com/koreader/koreader-base/pull/684#issuecomment-396710273), so the fork of koreader is un-buildable.

**Comment by Frenzie** [comment]
You could always submit a PR. ;-)

**Comment by lgeek** [comment]
Thanks for letting me know. A koreader update is long overdue, I might as well do it now.

**Comment by nguha** [comment]
@lgeek A koreader update would be much appreciated.
Thanks so much for all the effort you put into okreader and for releasing it as free software!
