### ISSUE TITLE
Clarify what is proprietary in the README

### ISSUE THREAD

**Issue by picsi** [lgeek/okreader#2]
The README briefly mentions that some parts of the firmware are proprietary. Could you clarify what proprietary software is needed to run the ebooks, even with okreader?

**Comment by lgeek** [comment]
There's a firmware blob used by the display controller to drive the electronic ink display. This is *not* distributed with okreader, it's loaded from the internal storage of the device by the bootloader.

The `firmware-okreader` package includes proprietary Broadcom firmware used by WiFi adapter, distributed under [this licence](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/LICENCE.broadcom_bcm43xx?id=b794c5039dcf0b7ebfeb58929d035f7a1d4c80dd).

**Comment by picsi** [comment]
Thanks.
