### ISSUE TITLE
lack of support for external sdcard booting

### ISSUE THREAD

**Issue by pazos** [lgeek/okreader#8]
support can be easy implemented for kobo touch, kobo glo, kobo aura hd and kobo aura h2o (any imx507 device with external sdcard)  I opened an issue on [uboot sources](https://github.com/lgeek/u-boot-okreader/issues/1) about this.

It is just a new environment for uboot, which repurposes light+power key combination(which, by default forces a factory reset) to boot from external sdcard.

As nickel, and some other software for kobos, want a fat32 filesytem on 1st partition of the external sdcard, the environment uses the second partition of the sdcard to use as rootfs

**Comment by lgeek** [comment]
I'm already using that key combination to boot okreader from the external card on my Aura. I thought this is how it works out of the box. Have I modified the boot script and forgot about it?

**Comment by pazos** [comment]
@lgeek: in my devices the key combo triggers a factory reset by using /dev/mmcblk0p2 as rootfs (which is indeed the recovery partition). I replace this partition with /dev/mmcblk1p2 (2nd partition on external sdcard). 
Modifying u-boot isn't enough to change this because uboot reads its environment from offset 768 (which isn't overwrriten with a new copy of uboot (flashed at offset 1 with size <= 500)

Could you please dump the first MB of your Aura and share it here?. Lets see which environment it has. (Really I just need a dump from offset 768 counting 128 bytes)

**Comment by lgeek** [comment]
In my Aura, it only triggers a factory reset if an external SD isn't plugged in, otherwise it boots from it. I don't have it on hand to dump the uboot environment now, but I intend to get around to it at some point.
